[database]
username = "forgottenserver"
password = "forgottenserver"

[worlds.world1]
id = 0
name = "World"
pvp-type = "pvp"
address-protected = "127.0.0.1"
port-protected = 7172
address-unprotected = "127.0.0.1"
port-unprotected = 7172
