[tool.poetry]
name = "ocelot"
version = "0.1.0"
description = ""
authors = ["Ranieri Althoff <ranisalt@gmail.com>"]

[tool.poetry.dependencies]
databases = { extras = ["mysql"], version = "^0.5.5" }
pydantic = "^1.9.1"
python = "^3.10"
starlette = "^0.20.0"
toml = "^0.10.2"
uvicorn = { extras = ["standard"], version = "^0.17.6" }

[tool.poetry.dev-dependencies]
black = { version = "*", allow-prereleases = true }
Faker = "^13.11.1"
httpx = "^0.22.0"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pytest-flake8 = "^1.1.1"
types-toml = "^0.10.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
